### ISSUE TITLE
unopenable files. 

### ISSUE THREAD

**Issue by 3dreefer** [fail0verflow/shofel2#12]
Fails compiling in SCAD, STL file fails and says incorrect format for slicers (Slic3r, S3D, Cura attempted). Also cannot open the STL as a mesh in Meshmixier nor Fusion360 to attempt to correct format error.

**Comment by c0d3m4st4** [comment]
You need to clone or download the repo to get the file OR open the stl file in github, switch to raw view and copy and paste the code in a txt file you later need to rename to stl.
