### ISSUE TITLE
"Error while loading shofel2\imx_usb.bat"

### ISSUE THREAD

**Issue by ethancawse** [fail0verflow/shofel2#20]
Hello, I am trying to install Linux on my Nintendo switch. While doing so, I encountered this error. Any help fast would be great. I am using Windows 10 x64. Also, I have a question. After installing Linux, can you return to stock firmware? Thank you. Here as an attached photo: 
![capture](https://user-images.githubusercontent.com/20261250/40259910-2f0ff05c-5ac6-11e8-9575-1a87e752ad3a.PNG)

**Comment by SwtcR** [comment]
I have no idea what this application is, but it isn't shofel2. Please contact its author, not us.
