### ISSUE TITLE
Having problems compiling the kernel

### ISSUE THREAD

**Issue by cokelito1** [fail0verflow/shofel2#3]
I im having problems compiling the kernel, specifically with all the blobs. after deleting all the blobs from the make menuconfig and use the imx usb loader there's a green screen that i suppose is a kernel panic because there's no driver, can you help me with this?

**Comment by SwtcR** [comment]
You need a UART debug console if you want to have any hopes of debugging issues before video works. You should build or buy a 1.8V USB to serial cable and connect it to the right side joy-con port connector.

**Comment by delroth** [comment]
@denysvitali the only blob we need at this point that's not upstream is a BCM firmware -- it can be found in multiple places on the internet though, pretty sure Arch has it in AUR.

We should probably document that step somewhere.

**Comment by denysvitali** [comment]
@delroth Is it the brcm4354 chip (w/ its respective blob)? If so, have you managed to use the bluetooth? at https://github.com/denysvitali/linux-on-pixel-c/issues/10 we were only able to use the Wi-Fi part of that chip

**Comment by delroth** [comment]
brcmfmac4356-pcie for us. I think @shuffle2 was successful in getting BT working but I haven't tried myself.

**Comment by denysvitali** [comment]
Ours is the sdio version, but it shouldn't be any different from the pcie one. We're having some troubles with the patchram thing. The issue #10 should clarify more on the problem

**Comment by cokelito1** [comment]
@SwtcR  i buy a usb to uart with 1 logical converter from 3.3 to 1.8 and 1.8 to 3.3, i have experience with arduino and raspberry pi, and programed some fpgs now my question is where is the pins for the usb to uart and which pin correspond to what, thank you
