### ISSUE TITLE
Compiling kernel

### ISSUE THREAD

**Issue by VioSynthax** [fail0verflow/shofel2#5]
> ~/Desktop/NS/linux$
>  make
> \  CHK     include/config/kernel.release
>   CHK     include/generated/uapi/linux/version.h
>   CHK     include/generated/utsrelease.h
>   CHK     include/generated/bounds.h
>   CHK     include/generated/timeconst.h
>   CHK     include/generated/asm-offsets.h
>   CALL    scripts/checksyscalls.sh
>   CHK     scripts/mod/devicetable-offsets.h
>   CHK     include/generated/compile.h
>   CHK     kernel/config_data.h
> make[1]: *** No rule to make target '/lib/firmware/brcm/brcmfmac4356-pcie.txt', needed by 'firmware/brcm/brcmfmac4356-pcie.txt.gen.o'.  Stop.
> Makefile:1048: recipe for target 'firmware' failed
> make: *** [firmware] Error 2

**Comment by natinusala** [comment]
Find the `bcmfmac4356-pcie.txt` file on the web and put it on `/lib/firmware/bcrm`. It fixed it for me.

**Comment by Y2K-x** [comment]
I managed to fix this by doing this:

1. Download `bcmfmac4356-pcie.txt` from https://chromium.googlesource.com/chromiumos/third_party/linux-firmware/+/f151f016b4fe656399f199e28cabf8d658bcb52b/brcm/brcmfmac4356-pcie.txt
2. Place `brcmfmac4356-pcie.txt` in `/lib/firmware/brcm/`. Create the firmware and brcm folders if you need to.
3. Run `sudo touch /lib/firmware/brcm/brcmfmac4356-pcie.txt`
4. `make`

Hope this helps!
