### ISSUE TITLE
Cannot compile target "firmware" because of a missing rule

### ISSUE THREAD

**Issue by natinusala** [fail0verflow/shofel2#7]
I followed the instructions on the README and when compiling Linux, the "firmware" target fails because of a missing rule :

```
natinusala@natinusala-GP70-2QE:~/shofel2/linux$ make
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CHK     include/generated/bounds.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  CHK     scripts/mod/devicetable-offsets.h
  CHK     include/generated/compile.h
  CHK     kernel/config_data.h
make[1]: ***  Aucune règle pour fabriquer la cible « /lib/firmware/nvidia/tegra210/vic04_ucode.bin », nécessaire pour « firmware/nvidia/tegra210/vic04_ucode.bin.gen.o ». Arrêt.
Makefile:1048 : la recette pour la cible « firmware » a échouée
make: *** [firmware] Erreur 2
```

**Comment by NightHammer1000** [comment]
Wich Distro are you using? Fixed it under debian by installing firmware-misc-nonfree

**Comment by natinusala** [comment]
I'm on Xubuntu. The package was not available on my apt sources and the deb wouldn't install because of a conflict, but I was able to install the missing tegra210 files manually by extracting them from the deb.

I also needed the bcrmfmac4356-pcie.txt file. I snatched it from the web as I couldn't find what package to install for this one.
